# Generated by Django 4.2.3 on 2023-08-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='image',
        ),
    ]
