# Generated by Django 4.2.3 on 2023-08-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
